# Continuous integration tests.

name: meltingpot-tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'examples/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'examples/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  pylint:
    name: Lint Melting Pot
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Set up Python 3.9
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run PyLint
        run: pylint --disable=C,W,R --recursive=y meltingpot examples

  run-meltingpot-tests:
    name: Test Melting Pot
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: ${{ github.event_name != 'workflow_dispatch' }}
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python-version:
          - '3.9'
          - '3.10'
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and test Melting Pot
        run: ./install.sh
