# Continuous integration tests.

name: meltingpot-tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'examples/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'examples/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint_and_typecheck:
    name: Lint and typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: ${{ github.event_name != 'workflow_dispatch' }}
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.9'
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint and typecheck Melting Pot
        uses: pre-commit/action@v3.0.0

  install_and_test:
    name: Install and test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: ${{ github.event_name != 'workflow_dispatch' }}
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python-version:
          - '3.9'
          - '3.10'
    steps:
      - name: Checkout Melting Pot
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and test Melting Pot
        run: ./install.sh
